name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: sudo apt install freeglut3-dev libglfw3 libglfw3 libglfw3-dev libglm-dev libassimp-dev assimp-utils libassimp-dev
    - name: unzip Glad
      run: unzip ./include/Glad.zip -d ./include/
    - name: compile
      run: make
